### ISSUE TITLE
Feature request: Show if pocketed issues/pulls are open, closed, or merged.

### ISSUE THREAD

**Issue by jamen** [egoist/github-pocket#2]
I imagine just a little icon on the right hand side that look like these ones:

![image](https://cloud.githubusercontent.com/assets/6251703/20082838/145956fc-a516-11e6-8e20-e60399480c82.png)

Would this be possible or do you think would be too many requests?

**Comment by egoist** [comment]
I guess it won't be too many requests, we can add a "load more" button, and show 5 items at a time

**Comment by kashav** [comment]
If work on this hasn't begun, I'd like take a stab at it!

Couldn't we just store the type along with the name? So instead of this -

```js
[
  "egoist/github-pocket/issues/2",
  "egoist/github-pocket", 
  "kshvmdn/some-private-repo"
]
```

it'd be -

```js
[
  { slug: "egoist/github-pocket/issues/2", type: "OPEN_ISSUE" },
  { slug: "egoist/github-pocket", type: "PUBLIC_REPO" },
  { slug: "kshvmdn/some-private-repo", type: "PRIVATE_REPO" }
]
```

and then we can use a simple object to map each type to it's respective icon.

Here are all the types I can think of:

```
OPEN_ISSUE
CLOSED_ISSUE
OPEN_PR
CLOSED_PR
MERGED_PR
PUBLIC_REPO
PRIVATE_REPO
PUBLIC_REPO_FORK
PRIVATE_REPO_FORK
```

**Comment by egoist** [comment]
@kshvmdn sounds good!
