### ISSUE TITLE
Publishing to Chrome Web Store

### ISSUE THREAD

**Issue by xxdavid** [egoist/github-pocket#3]
Hi,
I really like GitHub Pocket. But would you mind submitting it to the Chrome Web Store? I've got [mine](https://github.com/xxdavid/lastfm-friends-who-listen) there too. It requires you to pay one time fee of $5, but hey, that isn't that much.
I think your extension would gain some users this way.

Anyway, thank you for this extension!

**Comment by egoist** [comment]
Sorry I cannot make it there since I don't have a credit card (guess this is needed), so if you're interested I can add you to the repo and publish it if you want.

**Comment by xxdavid** [comment]
If it isn't a problem for you that it would be published under my name, I can submit it.

**Comment by egoist** [comment]
Sure, that's fine, I've added you to the repo too.

**Comment by xxdavid** [comment]
Thank you. I'll go ahead and publish it.

**Comment by xxdavid** [comment]
I've submitted it. It should be available in an hour or less.

**Comment by egoist** [comment]
cool, you can update the readme too when it's available 😃

**Comment by xxdavid** [comment]
Done. 🎉
